runtime: php55
api_version: 1

handlers:
- url: /images
  static_dir: images
  application_readable: true

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /.*
  script: index.php

